### ISSUE TITLE
A Radical Shift to Markdown and Jekyll

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aide_document#14]
Hi @AguaClara/aide_document,

I recently re-discovered an [extremely relevant post](https://jekyllrb.com/docs/datafiles/) about jekyll (a powerful static site generator). It talks about how you can add data files to your site and then reference them through variable names! And the data files can be json! I am strongly in favor of switching to markdown anyways, and this addin might just do the work for us. Let's talk about this next semester.

**Comment by ethan92429** [comment]
An update... Looks like the JinJa templating engine is Python's native templating engines. Apparently there is a whole world of templating engines out there... see [this wiki on them. ](https://en.wikipedia.org/wiki/Comparison_of_web_template_engines) With Jinja, we can make markdown files and use Jinja to intelligently inject variables, renderings, photos, etc...

**Comment by ethan92429** [comment]
hi @AguaClara/aide_document,

Please see the above ^ . Before jumping straight into Jekyll, I want to recommend a good long look at Jinja, which is Flask's templating engine. It is essentially Jekyll's liquid templating, but built in Python. We're using it currently to design the plants, and I think it may be easier if we were to use the same templating engine throughout the hole AIDE ecosystem. Here's a [quick primer.](https://realpython.com/blog/python/primer-on-jinja-templating/) Could someone make a comparison of the pros and cons for Jinja v. Liquid (Jekyll's system).

**Comment by ethan92429** [comment]
It would be the latest Jinja... Jinja2

**Comment by ethan92429** [comment]
Specifically, this should be a comparison between the two templating engines, Liquid and Jinja. No need to discuss Jekyll and Flask, which both have a number of other technologies built in, Jekyll being the Ruby-based version of Flask.

**Comment by urielAnneliese** [comment]
Hello, Ethan! The team have discussed the issue today and have come up the following comparison document. I believe the main problem of Flask is it might be hard to host it on Github.
https://docs.google.com/document/d/1NhgZ1ZO001flTBN056bm6hvfqBAN13Lz9Rj672Zrbi8/edit?usp=sharing
