### ISSUE TITLE
Github Issues Check #1

### ISSUE THREAD

**Issue by caseyching13** [AguaClara/aide_document#16]
See the rubric that was shared with you earlier in the semester for your Team's grade.

-Github issues needs work 
-What progress has the team made? What are setbacks? This should be reflected in the issues
-Timeline of when things on your task map should be accomplished/finished? Close issues as you complete tasks. (We have no way of gauging what progress has been made since there are no updates on Github issues!)
-All team members should be participating on Github issues
-Use Github to ask Ethan/Monroe/RA questions
-Track meetings with Ethan/Monroe/RA and what was discussed via issues
-Please have all members add their FULL NAME in their public profile
-Please incorporate suggestions in future Github Issues usage
-Next issues check will be in 2 weeks!

**Comment by oliver-leung** [comment]
As per Kevin's instructions, we'll be using our repo's issues page for more technical problems from now on. We're going to be updating our team page's [discussion board](https://github.com/orgs/AguaClara/teams/aide_document) with our progress and what we've done. We also need to meet/discuss with Ethan as to what our next steps are, so we'll be putting that on our discussion board as soon as we can.
