### ISSUE TITLE
Task completed so far

### ISSUE THREAD

**Issue by urielAnneliese** [AguaClara/aide_document#17]
This is the issue that keeps track of what we have done.

**Comment by urielAnneliese** [comment]
01/30 ~ 02/08
We worked on deploying a documentation GitHub page with Jekyll. 

* Note: This is suspended as the demand has changed.

**Comment by urielAnneliese** [comment]
02/08 ~ 02/13
We got familiar to Jinja2. Also, during this stage, a few meetings with Ethan happened discussing about the application of Jinja2.

**Comment by kevinjuan25** [comment]
@AguaClara/aide_document Don't put this in issues, please move to GitHub discussion for aide_document team

**Comment by urielAnneliese** [comment]
02/15 ~ 02/22
The repository was updated. A folder called JInja_playing, forked from the GUI team, was created to test on Jinja2 application.
