### ISSUE TITLE
Get ready for production 

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aide_document#21]
I think there are still a few things that keep this so it's not quite ready for production. First off, you should be using codecov and Travis for your development tools. See a tutorial on getting these working [here.](https://github.com/AguaClara/aide_tutorial/wiki/Tutorial:-Creating-a-New-Python-Package-Repository)

**Comment by ethan92429** [comment]
You also should be working in a virtual environment - meaning you should have an environment.yaml that defines that.

**Comment by oliver-leung** [comment]
For the virtual environment, is there anything specific that we should be configuring our environment with? We're not too familiar with using Conda environments.

**Comment by ethan92429** [comment]
Your environment should have only all the different packages necessary to work on, test, and publish your package. It is the environment that you are requiring developers to use when they work on your project. This should all be spec'd in your environment.yaml, created using [this](https://conda.io/docs/user-guide/tasks/manage-environments.html).

BTW, all of your builds are currently failing on Travis!
