### ISSUE TITLE
Use pytest for testing

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/aide_document#23]
Please write your tests using pytest. Here's a [tutorial](https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest) But practice using the conda virtual environment instead of virtualenv

**Comment by oliver-leung** [comment]
I've gotten pytest to work; just make sure you're within /tests so that the relative filepaths work. Some of them are failing, but that's expected because pdflatex isn't working right now on my computer.

I'll try to get TravisCI working soon!
