### ISSUE TITLE
Unrecognized characters when running translate (Windows)

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide_document#25]
When running translate from English to Spanish on my Windows 10 computer, it's unable to write accented characters (documentaci�n vs. documentación). I checked that both my Windows and Linux computers are on UTF-8.

I also tried encoding the strings and decoding them into ISO-8859-1, but that completely breaks the translation into Hindi.

**Comment by yilin-lu** [comment]
We are trying to put a utf-8 tag on the first line of the .py
